//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildersCapitalDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocStatusView
    {
        public System.Guid PropertyId { get; set; }
        public bool Agreement { get; set; }
        public bool Appraisal { get; set; }
        public bool SiteMap { get; set; }
        public bool Resume { get; set; }
        public bool Paperwork { get; set; }
    }
}
